name: w_module
version: 0.3.0
dev_dependencies:
  browser: "^0.10.0+2"
  coverage: "^0.7.2"
  dart_dev: "^1.0.0"
  dart_style: "^0.2.0"
  mockito: "^0.10.0"
  test: "^0.12.0"
  w_flux:
    git:
      url: git@github.com:Workiva/w_flux.git
      ref: 0.3.0
  web_skin_react:
    git:
      url: git@github.com:Workiva/web-skin-react.git
      ref: 2.1.4
